# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesslog',
            old_name='ForceOut',
            new_name='Force_Out',
        ),
        migrations.RenameField(
            model_name='acl',
            old_name='AllowedNodes',
            new_name='Allowed_Nodes',
        ),
        migrations.RenameField(
            model_name='securitynode',
            old_name='SiteOpen',
            new_name='Site_Open',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='DateAdded',
            new_name='Date_Added',
        ),
    ]
