# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20171220_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='Date_Added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='User',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
