# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_auto_20171220_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
