# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_auto_20171220_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='Out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
